# ==============================================================================
# Neurogym configuration template.
# This template contains all the variables supported by the configuration module.
# Please uncomment any variables that you would like to customise.
# ==============================================================================

# The local directory used for saving generated or downloaded data.
# If you uncomment this option, please replace the placeholder with a valid path.
# The default (<neurogym root>/local) is already in the .gitignore file,
# and therefore excluded from commits. If you change this, make sure that
# the custom path is either outside the repository tree or otherwise excluded
# from git commits.
# local_dir = <path-to-some-directory>

# ==================================================
# Agent configuration.
# ==================================================
[agent.training]

# Number of trials during training.
trials = 100

# Total number of steps during training.
steps = 100000

[agent.inference]

# Number of trials during training.
trials = 100

# Total number of steps during training.
steps = 100000

# ==================================================
# Environment configuration.
# ==================================================
[env]

# Name of the environment.
name = "TrialEnv"

# Time step duration.
dt = 10 # [ms]

# ==================================================
# Logging configuration.
# Logging relies on the Loguru library.
# Please check the documentation for Loguru at
# https://loguru.readthedocs.io/en/stable/api/logger.html#
# ==================================================
[monitor.log]

# Verbosity switch (switches logging on or off).
verbose = true

# Log format (passed to the Loguru configuration).
format = "<magenta>Neurogym</magenta> | <cyan>{time:YYYY-MM-DD@HH:mm:ss}</cyan> | <level>{message}</level>"

# Default log level.
# The options for this variable and the corresponding
# logger methods are as follows:
# TRACE: logger.trace()
# DEBUG: logger.debug()
# INFO: logger.info()
# SUCCESS: logger.success()
# WARNING: logger.warning()
# ERROR: logger.error()
# CRITICAL: logger.critical()
level = "INFO"

# Metric to use as a trigger for logging output.
# Possible options: 'trial', 'step'.
trigger = "trial"

# Logging interval.
# Tied to the 'trigger' option.
interval = 10

# ==================================================
# Configuration for plots produced during monitoring.
# ==================================================
[monitor.plot]

# Switch plotting on or off.
create = true

# Plot title.
title = "NeuroGym"

# Extension for plots saved as images.
ext = "png"

# Metric to use as a trigger for producing plots.
# Possible options: 'trial', 'step'.
trigger = "trial"

# Interval for creating plots.
# Tied to the 'trigger' option.
interval = 10
