# ==============================================================================
# NeuroGym configuration template
# This file defines all the customizable variables used by the configuration module.
# Uncomment and set only the variables you wish to override.
# ==============================================================================

# ==============================================================================
# General
# ==============================================================================

# Directory used to save output data (e.g., plots, logs, model checkpoints).
# The default is <neurogym root>/local.
# If you change this path, make sure it is outside your Git-controlled repository
# or excluded via .gitignore if you want to avoid tracking output data.
# local_dir = "/absolute/path/to/output"

# ==============================================================================
# Agent Configuration
# ==============================================================================

# Number of trials during training.
trials = 100

# Q: We should make sure that only one between trials and number of steps is used.
# Total number of steps during training.
steps = 100000

[agent.inference]

# Number of trials during training.
trials = 100

# Total number of steps during training.
steps = 100000

# Q: To be removed?

# ==============================================================================
# Environment Configuration
# ==============================================================================

[env]

# Name of the environment to use.
name = "TrialEnv"

# Time step duration in milliseconds.
dt = 10

# ==============================================================================
# Monitor Configuration
# ==============================================================================

[monitor]
# Optional custom name for the monitor.
# Q: Why could this name be different from 'Monitor'?
name = ""

# ==============================================================================
# Logging Configuration
# Logging is handled via Loguru (https://loguru.readthedocs.io/en/stable/)
# ==============================================================================

[monitor.log]

# Enable or disable logging.
verbose = true

# Log message format.
format = "<magenta>Neurogym</magenta> | <cyan>{time:YYYY-MM-DD@HH:mm:ss}</cyan> | <level>{message}</level>"

# Log level (options: TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL).
level = "INFO"

# Metric used to trigger logging output (options: 'trial', 'step').
# Q: `trigger` and `interval` are not used anywhere; what is their scope?
trigger = "trial"

# Number of units (based on trigger) between log messages.
interval = 10

# ==============================================================================
# Plotting Configuration
# ==============================================================================

[monitor.plot]

# Enable or disable plotting during monitoring.
create = true

# File extension for saved plots.
ext = "png"

# Metric used to trigger plotting (options: 'trial', 'step').
trigger = "trial"

# Number of units (based on trigger) between plots.
interval = 10

# Q: [TO BE REMOVED] Not used
# title = "NeuroGym"
